require conf/distro/amd-edf-small.conf

DISTRO = "xilinx-image-recovery"
DISTRO_NAME = "Image Recovery Distribution Configuration"

DISTRO_VERSION = "1.1"

DISTROOVERRIDES .= ":imgrcvry"

SDK_VENDOR = "-imgrcvrysdk"

MAINTAINER = "AMD AECG <meta-xilinx@yoctoproject.org>"

TARGET_VENDOR = "-imgrcvry"

PREFERRED_PROVIDER_virtual/bootloader = "u-boot-xlnx-imgrcvry"

MACHINE_FEATURES:remove = "optee"
