#@TYPE: Machine
#@NAME: versal-2ve-2vm-common
#@DESCRIPTION: Machine configuration for a common Versal Gen 2 filesystem devices

#### Preamble
MACHINEOVERRIDES =. "${@['', 'versal-2ve-2vm-common:']['versal-2ve-2vm-common' != '${MACHINE}']}"
#### Regular settings follow

DEFAULTTUNE = "cortexa72-cortexa53"

require conf/machine/versal-2ve-2vm-generic.conf

MACHINE_FEATURES += "\
    vcu2 \
    malig78ae \
    fpga-overlay \
    optee \
    "

#### No additional settings should be after the Postamble
#### Postamble
PACKAGE_EXTRA_ARCHS:append = "${@['', ' versal_2ve_2vm_common']['versal-2ve-2vm-common' != "${MACHINE}"]}"
